export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const countries = [
  {
    country: "Belarus",
    value: "belarus",
    currrency: "ruble",
    short: "BYR",
  },
  {
    country: "Brazil",
    value: "brazil",
    currency: "real",
    short: "RBL",
  },
  {
    country: "Canada",
    value: "canada",
    currency: "dollar",
    short: "CAD",
  },
  {
    country: "Eurozone",
    value: "eurozone",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "France",
    value: "france",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "Germany",
    value: "germany",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "Greece",
    value: "greece",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "India",
    value: "india",
    currency: "rupee",
    short: "RUP",
  },
  {
    country: "Japan",
    value: "japan",
    currency: "yen",
    short: "JPY",
  },
  {
    country: "Kazakhstan",
    value: "kazakhstan",
    currency: "tenge",
    short: "KZT",
  },
  {
    country: "Mexico",
    value: "mexico",
    currency: "peso",
    short: "MXN",
  },
  {
    country: "Russia",
    value: "russia",
    currency: "ruble",
    short: "RUB",
  },
  {
    country: "Spain",
    value: "spain",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "Turkey",
    value: "turkey",
    currency: "euro",
    short: "EUR",
  },
  {
    country: "Ukraine",
    value: "urkaine",
    currency: "hryvnia",
    short: "UAH",
  },
  {
    country: "United Kingdom",
    value: "united-kingdom",
    currency: "pound",
    short: "GBP",
  },
  {
    country: "United States",
    value: "united-states",
    currency: "dollar",
    short: "USD",
  },
];
